# Generated by Django 5.1.1 on 2024-09-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cv_academic_experience_profile_referee_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='e_office',
            new_name='e_cname',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='e_position',
            new_name='e_role',
        ),
    ]
