# Generated by Django 5.1.1 on 2024-09-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_e_office_experience_e_cname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='e_cname',
            new_name='e_name',
        ),
    ]
