# Generated by Django 5.1.1 on 2024-10-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_e_cname_experience_e_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referee',
            old_name='r_email',
            new_name='re_email',
        ),
        migrations.RenameField(
            model_name='referee',
            old_name='r_name',
            new_name='re_name',
        ),
        migrations.RenameField(
            model_name='referee',
            old_name='r_phone',
            new_name='re_phone',
        ),
    ]
