# Generated by Django 5.1.1 on 2024-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_r_email_referee_re_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lan1',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lan2',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
