# Generated by Django 5.1.1 on 2024-10-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_lan1_profile_lan2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lan1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lan2',
        ),
    ]
