# Generated by Django 5.1.1 on 2024-10-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
