# Generated by Django 5.1.1 on 2024-10-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_name',
            new_name='username',
        ),
    ]
